<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }

/**
 * Serves /llms.txt and merges Gleo's robots.txt addendum into core WordPress robots output.
 */
class Gleo_LLMs_Txt {
	public static function init() {
		add_filter( 'robots_txt', [ __CLASS__, 'filter_robots_txt' ], 20, 2 );
		add_action( 'init', [ __CLASS__, 'add_llms_rewrite' ] );
		add_action( 'parse_request', [ __CLASS__, 'maybe_serve_llms' ] );
	}

	public static function filter_robots_txt( $output, $public ) {
		$addendum = get_option( 'gleo_robots_addendum', '' );
		if ( ! empty( $addendum ) ) {
			$output .= $addendum;
		}
		return $output;
	}

	public static function add_llms_rewrite() {
		add_rewrite_rule( '^llms\.txt$', 'index.php?gleo_llms=1', 'top' );
		add_filter( 'query_vars', function( $vars ) {
			$vars[] = 'gleo_llms';
			return $vars;
		} );
	}

	public static function maybe_serve_llms( $wp ) {
		// Direct path matching — covers cases where rewrite rules haven't been flushed yet.
		$req = isset( $_SERVER['REQUEST_URI'] ) ? wp_parse_url( $_SERVER['REQUEST_URI'], PHP_URL_PATH ) : '';
		if ( $req === '/llms.txt' || ( isset( $wp->query_vars['gleo_llms'] ) && $wp->query_vars['gleo_llms'] ) ) {
			$content = get_option( 'gleo_llms_txt', '' );
			if ( empty( $content ) ) {
				status_header( 404 );
				exit;
			}
			header( 'Content-Type: text/plain; charset=utf-8' );
			header( 'X-Robots-Tag: noindex' );
			echo $content;
			exit;
		}
	}

	public static function generate() {
		$site_name = get_bloginfo( 'name' );
		$desc      = get_bloginfo( 'description' );
		$home      = home_url( '/' );

		$out  = "# $site_name\n\n";
		if ( $desc ) {
			$out .= "> $desc\n\n";
		}
		$out .= "$home\n\n";
		$out .= "## Key Pages\n\n";

		$priority = Gleo_Scanner::get_priority_posts( 15 );
		foreach ( $priority as $post ) {
			$title = get_the_title( $post );
			$url   = get_permalink( $post );
			$excerpt = wp_strip_all_tags( get_the_excerpt( $post ) );
			$excerpt = mb_substr( $excerpt, 0, 200 );
			$line = "- [$title]($url)";
			if ( $excerpt ) {
				$line .= ': ' . $excerpt;
			}
			$out .= $line . "\n";
		}

		$out .= "\n## About\n\n";
		$out .= "This file lists the canonical pages for $site_name in a format optimized for large language models.\n";
		$out .= "Generated by Gleo on " . current_time( 'Y-m-d' ) . ".\n";

		return $out;
	}
}
